# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXjPgAuV7d6TEX8nKWeSuPdXkjAejtiB
"""

import pandas as pd

data=pd.read_csv('/content/dataset p1.csv')
data

#check for null values
print(data.isnull().sum())

#filling the null CuoponCode --NoCoupon
data['CouponCode']=data['CouponCode'].fillna('NoCoupon')
data['Date']=pd.to_datetime(data['Date'])
print(data.isnull().sum())
print(data.dtypes)
print(data[data.duplicated()])

# checking for inconstitiencies
print(data['PaymentMethod'].unique())
print(data['OrderStatus'].unique())
print(data['ReferralSource'].unique())
print(data['CouponCode'].unique())

#check length
print(data['OrderID'].apply(len).unique())

#checking for errors
data.describe()

#rounding of the unit price to 2decimal places
data['UnitPrice']=data['UnitPrice'].round(2)
print(data['UnitPrice'].head())

# checking for outliers
import matplotlib.pyplot as plt
data.boxplot(column=['UnitPrice','TotalPrice'])
plt.show()
data.boxplot(column=['Quantity'])
plt.show()

data.to_csv('cleaned_dataset.csv',index=False)
from google.colab import files
files.download('cleaned_dataset.csv')

